includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - backbones/CifarResnet.yaml

data_root: /data/bzx_yjy/cifar100
image_size: 32
save_path: ./

# data
init_cls_num: 20
inc_cls_num: 20
task_num: 5

epoch: 80
device_ids: 0
n_gpu: 1
val_per_epoch: 5

batch_size: 128

optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 2e-4

lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [25, 50]



# done
backbone:
  name: resnet18
  kwargs:
    num_classes: 100
    args: 
      dataset: cifar100

buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 2000
    batch_size: 128
    strategy: herding      # random, equal_random, reservoir, herding 

classifier:
  name: bic
  kwargs:
    num_class: 100
    feat_dim: 512
    #feat_dim: 64
    init_cls_num: 20
    inc_cls_num: 20
    task_num: 5 #10

    optimizer:
      name: SGD
      kwargs:
        lr: 0.1
        weight_decay: 2e-4
        momentum: 0.9


   