includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - backbones/CifarResnet.yaml

data_root: /data/bzx_yjy/cifar100
image_size: 32
save_path: ./

# data
init_cls_num: 20
inc_cls_num: 20
task_num: 5

epoch: 1 #250
device_ids: 0
n_gpu: 1
val_per_epoch: 1
numworks: 1
split_ratio: 0.1

optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    weight_decay: 2e-4
    momentum: 0.9

lr_scheduler:
  name: StepLR
  kwargs:
    gamma: 0.5
    step_size: 10

# done
backbone:
  name: cifarresnet
  kwargs:
    num_classes: 100
    args: 
      dataset: cifar100

buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 0
    batch_size: 128
    strategy: random     # random, equal_random, reservoir, herding 

classifier:
  name: bic
  kwargs:
    num_class: 100
    #feat_dim: 256
    feat_dim: 64
    init_cls_num: 20
    inc_cls_num: 20
    task_num: 5 #10

    optimizer:
      name: SGD
      kwargs:
        lr: 0.1
        weight_decay: 2e-4
        momentum: 0.9


   